- name: Install redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: Ensure redis is enabled and running
  ansible.builtin.service:
    name: redis
    state: started
    enabled: true